// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Autore
{
    public int IdAutor { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Biografia { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public int IdNacionalidad { get; set; }

    public int IdSexo { get; set; }

    public virtual ICollection<AutoresLibro> AutoresLibros { get; set; } = new List<AutoresLibro>();

    public virtual Nacionalidade IdNacionalidadNavigation { get; set; }

    public virtual Sexo IdSexoNavigation { get; set; }
}