// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class AutoresLibro
{
    public int IdAutorLibro { get; set; }

    public int IdLibro { get; set; }

    public int IdAutor { get; set; }

    public virtual Autore IdAutorNavigation { get; set; }

    public virtual Libro IdLibroNavigation { get; set; }
}