// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Barrio
{
    public int IdBarrio { get; set; }

    public string Barrio1 { get; set; }

    public int IdCiudad { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    public virtual Ciudade IdCiudadNavigation { get; set; }
}