// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Categoria
{
    public int IdCategoria { get; set; }

    public string Categoria1 { get; set; }

    public virtual ICollection<LibrosCategoria> LibrosCategoria { get; set; } = new List<LibrosCategoria>();
}