// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Ciudade
{
    public int IdCiudad { get; set; }

    public string Ciudad { get; set; }

    public int IdProvincia { get; set; }

    public virtual ICollection<Barrio> Barrios { get; set; } = new List<Barrio>();

    public virtual Provincia IdProvinciaNavigation { get; set; }
}