// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Cliente
{
    public int CodCliente { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int NroDoc { get; set; }

    public int IdTipoDoc { get; set; }

    public int IdSexo { get; set; }

    public int IdNacionalidad { get; set; }

    public DateTime FechaRegistro { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public int IdBarrio { get; set; }

    public string Calle { get; set; }

    public int Nro { get; set; }

    public string Piso { get; set; }

    public string Dpto { get; set; }

    public string Cp { get; set; }

    public string Email { get; set; }

    public int? IdUsuario { get; set; }

    public virtual ICollection<Contacto> Contactos { get; set; } = new List<Contacto>();

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual ICollection<FormapagosCliente> FormapagosClientes { get; set; } = new List<FormapagosCliente>();

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual Nacionalidade IdNacionalidadNavigation { get; set; }

    public virtual Sexo IdSexoNavigation { get; set; }

    public virtual TiposDocumento IdTipoDocNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }

    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();
}