// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class DetalleFactura
{
    public int IdDetalleFactura { get; set; }

    public int Cantidad { get; set; }

    public decimal Precio { get; set; }

    public decimal? Recargo { get; set; }

    public int NroFactura { get; set; }

    public int CodLibro { get; set; }

    public virtual Libro CodLibroNavigation { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }
}