// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Editoriale
{
    public int IdEditorial { get; set; }

    public string Editorial { get; set; }

    public virtual ICollection<Libro> Libros { get; set; } = new List<Libro>();
}