// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class EstadosEnvio
{
    public int IdEstadoEnvio { get; set; }

    public string EstadoActual { get; set; }

    public virtual ICollection<TrackingEnvio> TrackingEnvios { get; set; } = new List<TrackingEnvio>();
}