// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class FacturasFormaspago
{
    public int IdFacturaPago { get; set; }

    public decimal MontoParcial { get; set; }

    public int IdFormaPago { get; set; }

    public int NroFactura { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }
}