// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Factura
{
    public int NroFactura { get; set; }

    public DateTime Fecha { get; set; }

    public DateTime FechaEntrega { get; set; }

    public DateTime FechaPago { get; set; }

    public int CodCliente { get; set; }

    public int IdFormaEnvio { get; set; }

    public decimal? CostoEnvio { get; set; }

    public virtual Cliente CodClienteNavigation { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual ICollection<FacturasFormaspago> FacturasFormaspagos { get; set; } = new List<FacturasFormaspago>();

    public virtual FormasEnvio IdFormaEnvioNavigation { get; set; }
}