// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Financiera
{
    public int IdFinanciera { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<FormapagosCliente> FormapagosClientes { get; set; } = new List<FormapagosCliente>();
}