// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class FormapagosCliente
{
    public int IdFormapagoCliente { get; set; }

    public int? NumTarjeta { get; set; }

    public DateOnly? FechaVencimiento { get; set; }

    public int? Cvv { get; set; }

    public int CodCliente { get; set; }

    public int IdFormaPago { get; set; }

    public int IdFinanciera { get; set; }

    public virtual Cliente CodClienteNavigation { get; set; }

    public virtual Financiera IdFinancieraNavigation { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }
}