// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class FormasPago
{
    public int IdFormaPago { get; set; }

    public string FormaPago { get; set; }

    public virtual ICollection<FacturasFormaspago> FacturasFormaspagos { get; set; } = new List<FacturasFormaspago>();

    public virtual ICollection<FormapagosCliente> FormapagosClientes { get; set; } = new List<FormapagosCliente>();
}