// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Genero
{
    public int IdGenero { get; set; }

    public string Genero1 { get; set; }

    public virtual ICollection<LibrosGenero> LibrosGeneros { get; set; } = new List<LibrosGenero>();
}