// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Idioma
{
    public int IdIdioma { get; set; }

    public string Idioma1 { get; set; }

    public virtual ICollection<Libro> Libros { get; set; } = new List<Libro>();
}