// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Libro
{
    public int CodLibro { get; set; }

    public string Isbn { get; set; }

    public string Titulo { get; set; }

    public decimal Precio { get; set; }

    public string Descripcion { get; set; }

    public int Stock { get; set; }

    public int IdEditorial { get; set; }

    public DateOnly FechaLanzamiento { get; set; }

    public int IdIdioma { get; set; }

    public virtual ICollection<AutoresLibro> AutoresLibros { get; set; } = new List<AutoresLibro>();

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual ICollection<DetallePedido> DetallePedidos { get; set; } = new List<DetallePedido>();

    public virtual Editoriale IdEditorialNavigation { get; set; }

    public virtual Idioma IdIdiomaNavigation { get; set; }

    public virtual ICollection<LibrosCategoria> LibrosCategoria { get; set; } = new List<LibrosCategoria>();

    public virtual ICollection<LibrosGenero> LibrosGeneros { get; set; } = new List<LibrosGenero>();
}