// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class LibrosCategoria
{
    public int IdLibroCategoria { get; set; }

    public int IdLibro { get; set; }

    public int IdCategoria { get; set; }

    public virtual Categoria IdCategoriaNavigation { get; set; }

    public virtual Libro IdLibroNavigation { get; set; }
}