// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class LibrosGenero
{
    public int IdLibroGenero { get; set; }

    public int IdLibro { get; set; }

    public int IdGenero { get; set; }

    public virtual Genero IdGeneroNavigation { get; set; }

    public virtual Libro IdLibroNavigation { get; set; }
}