// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Pedido
{
    public int NroPedido { get; set; }

    public DateTime Fecha { get; set; }

    public DateOnly FechaEntrega { get; set; }

    public string InstruccionesAdicionales { get; set; }

    public int CodCliente { get; set; }

    public int IdFormaEnvio { get; set; }

    public virtual Cliente CodClienteNavigation { get; set; }

    public virtual ICollection<DetallePedido> DetallePedidos { get; set; } = new List<DetallePedido>();

    public virtual FormasEnvio IdFormaEnvioNavigation { get; set; }

    public virtual ICollection<TrackingEnvio> TrackingEnvios { get; set; } = new List<TrackingEnvio>();
}