// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class TrackingEnvio
{
    public int IdTracking { get; set; }

    public int NroPedido { get; set; }

    public int IdEstadoEnvio { get; set; }

    public DateTime FechaEstado { get; set; }

    public string Observaciones { get; set; }

    public virtual EstadosEnvio IdEstadoEnvioNavigation { get; set; }

    public virtual Pedido NroPedidoNavigation { get; set; }
}