// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Libreria_API.Models;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string NombreUsuario { get; set; }

    public string ContrasenaHash { get; set; }

    public string Rol { get; set; }

    public DateTime? FechaAlta { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();
}